meta_product_name: "StartApp"
meta_title: "StartApp - Find your dream team"
meta_description: "Connect with top developers to bring your startup to life"
meta_image: "start-app--hero-img-OG.png"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
